### ISSUE TITLE
cleanup no longer survives cleanup

### ISSUE THREAD

**Issue by richfitz** [r-pkgs/processx#39]
I am trying to use processx to launch a background process that I can save the pid for.  On `master` I can specify `cleanup = FALSE` and the processx generated process survives the death of the parent process.  With the current code on `c` that does not happen (as of `ef93c72`)

```
px <- processx::process$new("sleep", "100000", cleanup = FALSE)
px$is_alive()
(pid <- px$get_pid())
# process alive - the R docs are wrong here - FALSE means alive :(
(tools::pskill(pid, 0))
rm(px)
gc()
# process has died
(tools::pskill(pid, 0))
```

**Comment by gaborcsardi** [comment]
Yes, sorry about that. I know about this, and it will be fixed soon. The `c` branch is in the works. The current development is on the `pipes` branch, but that is even more alpha.

**Comment by richfitz** [comment]
Cool, thanks. I'll revert back to master for the time being (which is great except that the reported pid is not the actual process)

**Comment by gaborcsardi** [comment]
Yeah, I guess the reported pid is the parent. No? The `master` branch uses some intermediate shell processes.

**Comment by richfitz** [comment]
That's right; on osx at least the "real" pid is that plus one but I'd not like to rely on that and will just wait for your rewrite to stabilise

**Comment by gaborcsardi** [comment]
Yeah, you would need to query the children of that process.

**Comment by gaborcsardi** [comment]
@richfitz So, because in the new version there is no intermediate shell process, it is a bit trickier to start up daemon(-like) processes. 

Can you please elaborate your use case a bit? Do you want to start a background process, that keeps running after you quit form R? Do you also want to detach from the controlling terminal?

I am thinking about having a `daemon = TRUE` option, that is equivalent to a `daemon()` call.
